### ISSUE TITLE
Redesign for settings page

### ISSUE THREAD

**Issue by happylolonly** [HappyCodeHere/events-spa-server#25]
Need to add styles for settings page. Cause now them are too poor;)

1. Add styles for `Checkbox` component. It should be custom styled checkbox with site's main color - `constant/style/color`
2. Add links near checkboxes.
3. Update button 'Загрузить на весь день'. And maybe description.
4. At main `index.scss` add some styles for `h5`
5. Maybe something else;)

![image](https://user-images.githubusercontent.com/18665326/50792012-a90bcb80-12d4-11e9-8804-bc353f228d3a.png)

**Comment by raven41k** [comment]
I will take this task

**Comment by happylolonly** [comment]
@raven41k , very thanks!)
