### ISSUE TITLE
Button for scrolling page up

### ISSUE THREAD

**Issue by happylolonly** [HappyCodeHere/events-spa-server#4]
Необходимо предложить вариант и сделать кнопку проскролливания экрана вверх после просмотра пользователем нескольких мероприятий на странице /events.

Вариант можно посмотреть, например, в группе в вк.
![image](https://user-images.githubusercontent.com/18665326/49762005-8d170900-fcd9-11e8-8907-99c46782fa78.png)

Заготовка есть тут: `/client/src/components/ScrollUpButton`

**Comment by happylolonly** [comment]
@Chechko-Ivan , nice!)

**Comment by Semigradsky** [comment]
@happylolonly  It scrolls soooo long. Maybe increase speed?
